"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#configuracion de ruta de los templates
import os

#pip install python-dotenv
try:
    from dotenv import load_dotenv
    load_dotenv(os.path.join(BASE_DIR, ".env"))
except Exception:
    pass

#pip install pymysql
if os.getenv("USE_PYMYSQL", "0") == "1":
 import pymysql
 pymysql.install_as_MySQLdb()

#Determinar entorno actual (local o producción)
ENV = os.getenv("ENV", "local")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "inseguro_para_dev")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG","True")== "True"

# Permitir conexiones desde cualquier host en desarrollo, en producción especificar los hosts permitidos
if ENV == "production":
    ALLOWED_HOSTS = ["*"]  # o tu dominio Railway si lo prefieres
else:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware', #middleware de CORS
]

ROOT_URLCONF = 'djang0.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], #aqui agregamos la configuracion de ruta de los templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static', #para archivos estaticos
            ],
        },
    },
]

WSGI_APPLICATION = 'djang0.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración dinámica de base de datos
if ENV == "production":
    DATABASES = {
        'default': {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("MYSQL_DATABASE"),  # Use MYSQL_DATABASE
            "USER": os.getenv("MYSQL_USER"),      # Use MYSQL_USER
            "PASSWORD": os.getenv("MYSQL_PASSWORD"),  # Use MYSQL_PASSWORD
            "HOST": os.getenv("MYSQL_HOST"),      # Use MYSQL_HOST
            "PORT": int(os.getenv("MYSQL_PORT", "3306")),  # Convert to integer
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            **(
                {"ssl": {"ca": os.getenv("MYSQL_SSL_CA")}}
                if os.getenv("MYSQL_SSL_CA")
                else {}
                ),    
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es' #Idioma español

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#Configuracion de archivos estaticos
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#pip install djangorestframework-simplejwt
#Esto indica que todas las solicitudes a la API deben usar JWT para autenticación.
REST_FRAMEWORK = { 
    'DEFAULT_PERMISSION_CLASSES': ( 
        'rest_framework.permissions.AllowAny', # Requiere que el usuario esté autenticado para acceder a la API,
                                                      # hace todas las vistas privadas # IsAuthenticated o AllowAny
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': ( 
       'rest_framework_simplejwt.authentication.JWTAuthentication', 
    ) 
} 
#pip install django-cors-headers
CORS_ALLOW_ALL_ORIGINS = True #Permitir solicitudes CORS