# Generated by Django 5.2.6 on 2025-10-15 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaMatrona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_consulta', models.IntegerField()),
                ('detalle', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('matrona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='app.madre')),
            ],
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('natural', 'Natural'), ('cesarea', 'Cesárea'), ('instrumental', 'Instrumental')], max_length=20)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_termino', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('cirujano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partos_dirigidos', to=settings.AUTH_USER_MODEL)),
                ('equipo_asignado', models.ManyToManyField(blank=True, related_name='partos_participantes', to=settings.AUTH_USER_MODEL)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.madre')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackJefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('jefe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.parto')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.FloatField(null=True)),
                ('peso', models.FloatField(default=0)),
                ('temperatura', models.FloatField()),
                ('presion', models.CharField(max_length=20)),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('enfermero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitales', to='app.madre')),
            ],
        ),
    ]
