# Generated by Django 5.2.6 on 2025-10-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parto',
            old_name='cirujano',
            new_name='medico',
        ),
    ]
